### ISSUE TITLE
Weird generator behaviour with :length's check ((:min & :max) or :in)

### ISSUE THREAD

**Issue by madeinussr** [madeinussr/exop_props#7]
Random test (which depend on `:length` check) fail, for example:

test/exop_props/params_generator/map_test.exs:115
test/exop_props/params_generator/list_test.exs:175

Those tests fail because instead of generating types which were defined in check `:type` a generator generates random type (seems like `term`).

**Comment by madeinussr** [comment]
will see

**Comment by llxff** [comment]
let's close it for now
